services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: frontend.dockerfile
  #   image: marcusan-app-img
  #   container_name: marcusan-app
  #   ports:
  #     - "80:80"
  #   network:
  #     - marcusan_network
  #   depends_on:
  #     - server

  server:
    build:
      context: .
      dockerfile: backend.dockerfile
    image: marcusan-server-img
    container_name: marcusan-server
    env_file:
      - ./backend/.env
    environment:
      DEEPFACE_HOME: /app/deepface
    ports:
      - "8000:8000"
    networks:
      - marcusan_network
    volumes:
      - deepface:/app/deepface
    depends_on:
      postgres_db:
        condition: service_healthy
  
  postgres_db:
    image: pgvector/pgvector:pg17
    container_name: marcusan-pgdb
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    networks:
      - marcusan_network
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  pgdata:
    name: marcusan-pgdata
  deepface:
    name: marcusan-deepface-data

networks:
  marcusan_network:
    name: marcusan-network
    driver: bridge